version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    file_exists_behavior: OVERWRITE 
permissions:
  - object: /usr/share/nginx/html
    pattern: "**"
    owner: ec2-user  # 또는 root
    group: ec2-user  # 또는 root
    mode: 775        # 권한을 조금 더 넉넉히 줍니다